# Generated by Django 5.0.6 on 2024-07-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap3', '0002_alter_course_course_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_code', models.CharField(max_length=100)),
                ('meeting_dt', models.DateField(auto_now_add=True)),
                ('meeting_subject', models.CharField(max_length=100)),
                ('meeting_np', models.IntegerField()),
            ],
        ),
    ]
